mod common;

use binwalk_ng::formats::cpio::cpio_parser;
use binwalk_ng::signatures::CONFIDENCE_HIGH;

const SIGNATURE_TYPE: &str = "cpio";
const INPUT_FILE_NAME: &str = "cpio.newc.cpio";

#[test]
fn integration_test() {
    common::integration_test(SIGNATURE_TYPE, INPUT_FILE_NAME);
}

/// Fixture is the samples repo's `cpio.newc.cpio`, generated by GNU cpio's
/// newc format (see the samples repo's generate_samples.py).
///
/// The expected size is derived independently of the parser, from the newc
/// on-disk layout alone (`trailer_record_end` below): hardcoding a number
/// copied from the parser's own output would enshrine an off-by-alignment
/// bug rather than guard against one (this exact mistake slipped through an
/// earlier revision -- see the PR #104 review discussion).
#[test]
fn reports_pinned_size_and_file_count() {
    let results = common::run_binwalk(SIGNATURE_TYPE, INPUT_FILE_NAME);

    assert_eq!(results.file_map.len(), 1);
    let signature = &results.file_map[0];
    assert_eq!(signature.offset, 0);
    assert_eq!(signature.confidence, CONFIDENCE_HIGH);

    // The archive's data ends with the complete TRAILER!!! record...
    let expected_end = trailer_record_end(&fixture());
    assert_eq!(signature.size, expected_end);

    // ...GNU cpio then pads the output file out to 512-byte blocks, so the
    // reported size must not include that padding. (If the records already end
    // on a block boundary there is no padding, and nothing to check.)
    let block_padded_end = expected_end.next_multiple_of(512);
    if block_padded_end > expected_end {
        assert_ne!(
            signature.size, block_padded_end,
            "reported size includes GNU cpio's end-of-archive block padding"
        );
    }

    assert_eq!(signature.description, "CPIO ASCII archive, file count: 1");
}

fn fixture() -> Vec<u8> {
    std::fs::read(std::path::Path::new(common::SAMPLES_DIR).join(INPUT_FILE_NAME)).unwrap()
}

/// Offset of the TRAILER!!! entry, found independently of the parser: the entry
/// header is 110 bytes long and the trailer name is the last occurrence of
/// "TRAILER!!!" in the archive.
fn trailer_start(data: &[u8]) -> usize {
    data.windows(10).rposition(|w| w == b"TRAILER!!!").unwrap() - 110
}

/// End offset of the complete TRAILER!!! record in a newc archive, derived
/// from the format's on-disk layout alone: a 110-byte header followed by the
/// NUL-terminated entry name ("TRAILER!!!" + '\0'), with the header+name block
/// rounded up to newc's 4-byte alignment. The trailer carries no file data.
///
/// This is the boundary a conforming parser must report as the archive size --
/// everything after it is GNU cpio's 512-byte end-of-archive block padding.
fn trailer_record_end(data: &[u8]) -> usize {
    const NEWC_HEADER_SIZE: usize = 110;
    const TRAILER_NAME_LEN: usize = "TRAILER!!!\0".len(); // includes NUL terminator

    let header_and_name = NEWC_HEADER_SIZE + TRAILER_NAME_LEN;
    trailer_start(data) + header_and_name + pad4(header_and_name)
}

/// newc pads each entry's header+name block and its data to 4-byte boundaries.
const fn pad4(n: usize) -> usize {
    match n % 4 {
        0 => 0,
        remainder => 4 - remainder,
    }
}

#[test]
fn rejects_corrupted_magic() {
    let mut data = fixture();
    data[..6].copy_from_slice(b"XXXXXX");

    assert!(cpio_parser(&data, 0).is_err());
}

#[test]
fn rejects_truncated_archive() {
    let data = fixture();

    assert!(cpio_parser(&data[..100], 0).is_err());
    assert!(cpio_parser(&data[..300], 0).is_err());
}

#[test]
fn rejects_archive_without_trailer() {
    let data = fixture();
    let trailer_start = trailer_start(&data);

    assert!(cpio_parser(&data[..trailer_start], 0).is_err());
}

#[test]
fn rejects_trailer_only_archive() {
    let data = fixture();
    let trailer_start = trailer_start(&data);

    assert!(cpio_parser(&data[trailer_start..], 0).is_err());
}

#[test]
fn rejects_non_hex_size_fields() {
    let mut data = fixture();
    data[54..62].copy_from_slice(b"ZZZZZZZZ"); // file size field
    assert!(cpio_parser(&data, 0).is_err());

    let mut data = fixture();
    data[94..102].copy_from_slice(b"ZZZZZZZZ"); // name size field
    assert!(cpio_parser(&data, 0).is_err());
}

#[test]
fn rejects_invalid_utf8_file_name() {
    let mut data = fixture();
    data[94..102].copy_from_slice(b"00000004");
    data[110..113].copy_from_slice(b"\xFF\xFE\x00");

    assert!(cpio_parser(&data, 0).is_err());
}
