mod common;

use binwalk_ng::formats::rar::extract_rar;
use std::fs;
use std::path::Path;

// ── integration test ─────────────────────────────────────────────────────────

/// Full binwalk pipeline: signature detection + internal extraction of the RAR
/// fixture in tests/inputs/rar.bin.
///
/// This test verifies that binwalk's RAR signature and extractor work together
/// end-to-end: the file is detected, the native `rars`-based extractor runs,
/// and the result is reported as successful.
#[test]
fn integration_test() {
    const SIGNATURE_TYPE: &str = "rar";
    const INPUT_FILE_NAME: &str = "rar.bin";
    common::integration_test(SIGNATURE_TYPE, INPUT_FILE_NAME);
}

// ── extraction content tests ─────────────────────────────────────────────────

/// End-to-end content verification: the extractor must produce exactly the
/// files present in the RAR5 fixture with exactly the right contents.
///
/// The fixture (tests/inputs/rar.bin) was generated by gen_rar.sh and contains:
///   - testdir/          (directory)
///   - testdir/hello.txt (file, "Hello, RAR!\n")
#[test]
fn extraction_produces_expected_files() {
    let outdir = tempfile::tempdir().unwrap();
    let input_path = Path::new("tests").join("inputs").join("rar.bin");

    let file_data = fs::read(&input_path).expect("failed to read tests/inputs/rar.bin");
    let result = extract_rar(&file_data, 0, Some(outdir.path()));

    assert!(result.success, "extraction must succeed");

    // The extracted file must exist and contain the pinned content.
    let hello_txt = outdir.path().join("testdir").join("hello.txt");
    assert!(
        hello_txt.exists(),
        "expected testdir/hello.txt to be extracted"
    );
    assert_eq!(
        fs::read(&hello_txt).unwrap(),
        b"Hello, RAR!\n",
        "contents of testdir/hello.txt mismatch"
    );

    // The directory entry must have been created.
    let testdir = outdir.path().join("testdir");
    assert!(testdir.is_dir(), "expected testdir/ directory to be created");
}

/// Extracting the same archive twice to different output directories must
/// succeed both times (no cross-contamination or shared state).
#[test]
fn extraction_is_repeatable() {
    let input_path = Path::new("tests").join("inputs").join("rar.bin");
    let file_data = fs::read(&input_path).expect("failed to read tests/inputs/rar.bin");

    let outdir1 = tempfile::tempdir().unwrap();
    let outdir2 = tempfile::tempdir().unwrap();

    let r1 = extract_rar(&file_data, 0, Some(outdir1.path()));
    let r2 = extract_rar(&file_data, 0, Some(outdir2.path()));

    assert!(r1.success, "first extraction must succeed");
    assert!(r2.success, "second extraction must succeed");

    // Both output trees must contain the expected file.
    assert!(outdir1.path().join("testdir/hello.txt").exists());
    assert!(outdir2.path().join("testdir/hello.txt").exists());
}
