use crate::extractors;
use crate::formats;
use crate::signatures;

/// Returns a list of all supported signatures, including their "magic" byte patterns, parser functions, and any associated extractor.
pub fn patterns() -> Vec<signatures::Signature> {
    let binary_signatures: Vec<signatures::Signature> = vec![
        // gzip
        signatures::Signature {
            name: "gzip".to_string(),
            short: false,
            magic_offset: 0,
            always_display: false,
            magic: formats::gzip::gzip_magic(),
            parser: formats::gzip::gzip_parser,
            description: formats::gzip::DESCRIPTION.to_string(),
            extractor: Some(formats::gzip::gzip_extractor()),
        },
        // .deb
        signatures::Signature {
            name: "deb".to_string(),
            short: false,
            magic_offset: 0,
            always_display: false,
            magic: formats::deb::deb_magic(),
            parser: formats::deb::deb_parser,
            description: formats::deb::DESCRIPTION.to_string(),
            extractor: None,
        },
        // 7-zip
        signatures::Signature {
            name: "7zip".to_string(),
            short: false,
            magic_offset: 0,
            always_display: false,
            magic: formats::sevenzip::sevenzip_magic(),
            parser: formats::sevenzip::sevenzip_parser,
            description: formats::sevenzip::DESCRIPTION.to_string(),
            extractor: Some(formats::sevenzip::sevenzip_extractor()),
        },
        // xz
        signatures::Signature {
            name: "xz".to_string(),
            short: false,
            magic_offset: 0,
            always_display: false,
            magic: formats::xz::xz_magic(),
            parser: formats::xz::xz_parser,
            description: formats::xz::DESCRIPTION.to_string(),
            extractor: Some(formats::lzma::lzma_extractor()),
        },
        // tarball
        signatures::Signature {
            name: "tarball".to_string(),
            short: false,
            magic_offset: 0,
            always_display: false,
            magic: formats::tarball::tarball_magic(),
            parser: formats::tarball::tarball_parser,
            description: formats::tarball::DESCRIPTION.to_string(),
            extractor: Some(formats::tarball::tarball_extractor()),
        },
        // squashfs
        signatures::Signature {
            name: "squashfs".to_string(),
            short: false,
            magic_offset: 0,
            always_display: false,
            magic: formats::squashfs::squashfs_magic(),
            parser: formats::squashfs::squashfs_parser,
            description: formats::squashfs::DESCRIPTION.to_string(),
            extractor: Some(formats::squashfs::squashfs_extractor()),
        },
        // dlob
        signatures::Signature {
            name: "dlob".to_string(),
            short: false,
            magic_offset: 0,
            always_display: false,
            magic: formats::dlob::dlob_magic(),
            parser: formats::dlob::dlob_parser,
            description: formats::dlob::DESCRIPTION.to_string(),
            extractor: None,
        },
        // lzma
        signatures::Signature {
            name: "lzma".to_string(),
            short: false,
            magic_offset: 0,
            always_display: false,
            magic: formats::lzma::lzma_magic(),
            parser: formats::lzma::lzma_parser,
            description: formats::lzma::DESCRIPTION.to_string(),
            //extractor: Some(formats::sevenzip::sevenzip_extractor()),
            extractor: Some(formats::lzma::lzma_extractor()),
        },
        // Fritz!Box EVA kernel image (TI record format, LZMA-compressed)
        signatures::Signature {
            name: "eva".to_string(),
            short: false,
            magic_offset: 0,
            always_display: false,
            magic: formats::eva::eva_magic(),
            parser: formats::eva::eva_parser,
            description: formats::eva::DESCRIPTION.to_string(),
            extractor: Some(formats::eva::eva_extractor()),
        },
        // bmp
        signatures::Signature {
            name: "bmp".to_string(),
            short: false,
            magic_offset: 0,
            always_display: false,
            magic: formats::bmp::bmp_magic(),
            parser: formats::bmp::bmp_parser,
            description: formats::bmp::DESCRIPTION.to_string(),
            extractor: Some(formats::bmp::bmp_extractor()),
        },
        // bzip2
        signatures::Signature {
            name: "bzip2".to_string(),
            short: false,
            magic_offset: 0,
            always_display: false,
            magic: formats::bzip2::bzip2_magic(),
            parser: formats::bzip2::bzip2_parser,
            description: formats::bzip2::DESCRIPTION.to_string(),
            extractor: Some(formats::bzip2::bzip2_extractor()),
        },
        // uimage
        signatures::Signature {
            name: "uimage".to_string(),
            short: false,
            magic_offset: 0,
            always_display: false,
            magic: formats::uimage::uimage_magic(),
            parser: formats::uimage::uimage_parser,
            description: formats::uimage::DESCRIPTION.to_string(),
            extractor: Some(formats::uimage::uimage_extractor()),
        },
        // packimg header
        signatures::Signature {
            name: "packimg".to_string(),
            short: false,
            magic_offset: 0,
            always_display: false,
            magic: formats::packimg::packimg_magic(),
            parser: formats::packimg::packimg_parser,
            description: formats::packimg::DESCRIPTION.to_string(),
            extractor: None,
        },
        // crc32 constants
        signatures::Signature {
            name: "crc32".to_string(),
            short: false,
            magic_offset: 0,
            always_display: false,
            magic: formats::hashes::crc32_magic(),
            parser: formats::hashes::crc32_parser,
            description: formats::hashes::CRC32_DESCRIPTION.to_string(),
            extractor: None,
        },
        // sha256 constants
        signatures::Signature {
            name: "sha256".to_string(),
            short: false,
            magic_offset: 0,
            always_display: false,
            magic: formats::hashes::sha256_magic(),
            parser: formats::hashes::sha256_parser,
            description: formats::hashes::SHA256_DESCRIPTION.to_string(),
            extractor: None,
        },
        // cpio
        signatures::Signature {
            name: "cpio".to_string(),
            short: false,
            magic_offset: 0,
            always_display: false,
            magic: formats::cpio::cpio_magic(),
            parser: formats::cpio::cpio_parser,
            description: formats::cpio::DESCRIPTION.to_string(),
            extractor: Some(formats::sevenzip::sevenzip_extractor()),
        },
        // iso9660 primary volume
        signatures::Signature {
            name: "iso9660".to_string(),
            short: false,
            magic_offset: 0,
            always_display: false,
            magic: formats::iso9660::iso_magic(),
            parser: formats::iso9660::iso_parser,
            description: formats::iso9660::DESCRIPTION.to_string(),
            extractor: Some(formats::iso9660::iso9660_extractor()),
        },
        // linux kernel
        signatures::Signature {
            name: "linux_kernel".to_string(),
            short: false,
            magic_offset: 0,
            always_display: true,
            magic: formats::linux::linux_kernel_version_magic(),
            parser: formats::linux::linux_kernel_version_parser,
            description: formats::linux::LINUX_KERNEL_VERSION_DESCRIPTION.to_string(),
            extractor: Some(formats::linux::linux_kernel_extractor()),
        },
        // linux boot image
        signatures::Signature {
            name: "linux_boot_image".to_string(),
            short: false,
            magic_offset: 0,
            always_display: false,
            magic: formats::linux::linux_boot_image_magic(),
            parser: formats::linux::linux_boot_image_parser,
            description: formats::linux::LINUX_BOOT_IMAGE_DESCRIPTION.to_string(),
            extractor: None,
        },
        // linux arm zimage
        signatures::Signature {
            name: "linux_arm_zimage".to_string(),
            short: false,
            magic_offset: 0,
            always_display: false,
            magic: formats::linux::linux_arm_zimage_magic(),
            parser: formats::linux::linux_arm_zimage_parser,
            description: formats::linux::LINUX_ARM_ZIMAGE_DESCRIPTION.to_string(),
            extractor: None,
        },
        // zstd
        signatures::Signature {
            name: "zstd".to_string(),
            short: false,
            magic_offset: 0,
            always_display: false,
            magic: formats::zstd::zstd_magic(),
            parser: formats::zstd::zstd_parser,
            description: formats::zstd::DESCRIPTION.to_string(),
            extractor: Some(formats::zstd::zstd_extractor()),
        },
        // zip
        signatures::Signature {
            name: "zip".to_string(),
            short: false,
            magic_offset: 0,
            always_display: false,
            magic: formats::zip::zip_magic(),
            parser: formats::zip::zip_parser,
            description: formats::zip::DESCRIPTION.to_string(),
            extractor: Some(formats::sevenzip::sevenzip_extractor()),
        },
        // Intel PCH ROM
        signatures::Signature {
            name: "pchrom".to_string(),
            short: false,
            magic_offset: 0,
            always_display: false,
            magic: formats::pchrom::pch_rom_magic(),
            parser: formats::pchrom::pch_rom_parser,
            description: formats::pchrom::DESCRIPTION.to_string(),
            extractor: Some(formats::uefi::uefi_extractor()),
        },
        // UEFI PI volume
        signatures::Signature {
            name: "uefi_pi_volume".to_string(),
            short: false,
            magic_offset: 0,
            always_display: false,
            magic: formats::uefi::uefi_volume_magic(),
            parser: formats::uefi::uefi_volume_parser,
            description: formats::uefi::VOLUME_DESCRIPTION.to_string(),
            extractor: Some(formats::uefi::uefi_extractor()),
        },
        // UEFI capsule image
        signatures::Signature {
            name: "uefi_capsule".to_string(),
            short: false,
            magic_offset: 0,
            always_display: false,
            magic: formats::uefi::uefi_capsule_magic(),
            parser: formats::uefi::uefi_capsule_parser,
            description: formats::uefi::CAPSULE_DESCRIPTION.to_string(),
            extractor: Some(formats::uefi::uefi_extractor()),
        },
        // PDF document
        signatures::Signature {
            name: "pdf".to_string(),
            short: false,
            magic_offset: 0,
            always_display: false,
            magic: formats::pdf::pdf_magic(),
            parser: formats::pdf::pdf_parser,
            description: formats::pdf::DESCRIPTION.to_string(),
            extractor: None,
        },
        // ELF
        signatures::Signature {
            name: "elf".to_string(),
            short: false,
            magic_offset: 0,
            always_display: false,
            magic: formats::elf::elf_magic(),
            parser: formats::elf::elf_parser,
            description: formats::elf::DESCRIPTION.to_string(),
            extractor: None,
        },
        // CramFS
        signatures::Signature {
            name: "cramfs".to_string(),
            short: false,
            magic_offset: 0,
            always_display: false,
            magic: formats::cramfs::cramfs_magic(),
            parser: formats::cramfs::cramfs_parser,
            description: formats::cramfs::DESCRIPTION.to_string(),
            extractor: Some(formats::sevenzip::sevenzip_extractor()),
        },
        // QNX IFS
        // TODO: The signature and extractor are untested. Need a sample IFS image.
        signatures::Signature {
            name: "qnx_ifs".to_string(),
            short: false,
            magic_offset: 0,
            always_display: false,
            magic: formats::qnx::qnx_ifs_magic(),
            parser: formats::qnx::qnx_ifs_parser,
            description: formats::qnx::IFS_DESCRIPTION.to_string(),
            extractor: Some(extractors::dumpifs::dumpifs_extractor()),
        },
        // RomFS
        signatures::Signature {
            name: "romfs".to_string(),
            short: false,
            magic_offset: 0,
            always_display: false,
            magic: formats::romfs::romfs_magic(),
            parser: formats::romfs::romfs_parser,
            description: formats::romfs::DESCRIPTION.to_string(),
            extractor: Some(formats::romfs::romfs_extractor()),
        },
        // EXT
        signatures::Signature {
            name: "ext".to_string(),
            short: false,
            magic_offset: 0,
            always_display: false,
            magic: formats::ext::ext_magic(),
            parser: formats::ext::ext_parser,
            description: formats::ext::DESCRIPTION.to_string(),
            extractor: Some(extractors::tsk::tsk_extractor()),
        },
        // CAB archive
        signatures::Signature {
            name: "cab".to_string(),
            short: false,
            magic_offset: 0,
            always_display: false,
            magic: formats::cab::cab_magic(),
            parser: formats::cab::cab_parser,
            description: formats::cab::DESCRIPTION.to_string(),
            extractor: Some(formats::cab::cab_extractor()),
        },
        // JFFS2
        signatures::Signature {
            name: "jffs2".to_string(),
            short: false,
            magic_offset: 0,
            always_display: false,
            magic: formats::jffs2::jffs2_magic(),
            parser: formats::jffs2::jffs2_parser,
            description: formats::jffs2::DESCRIPTION.to_string(),
            extractor: Some(formats::jffs2::jffs2_extractor()),
        },
        // YAFFS
        signatures::Signature {
            name: "yaffs".to_string(),
            short: false,
            magic_offset: 0,
            always_display: false,
            magic: formats::yaffs::yaffs_magic(),
            parser: formats::yaffs::yaffs_parser,
            description: formats::yaffs::DESCRIPTION.to_string(),
            extractor: Some(formats::yaffs::yaffs2_extractor()),
        },
        // lz4
        signatures::Signature {
            name: "lz4".to_string(),
            short: false,
            magic_offset: 0,
            always_display: false,
            magic: formats::lz4::lz4_magic(),
            parser: formats::lz4::lz4_parser,
            description: formats::lz4::DESCRIPTION.to_string(),
            extractor: Some(formats::lz4::lz4_extractor()),
        },
        // lzop
        signatures::Signature {
            name: "lzop".to_string(),
            short: false,
            magic_offset: 0,
            always_display: false,
            magic: formats::lzop::lzop_magic(),
            parser: formats::lzop::lzop_parser,
            description: formats::lzop::DESCRIPTION.to_string(),
            extractor: Some(formats::lzop::lzop_extractor()),
        },
        // lzop
        signatures::Signature {
            name: "pe".to_string(),
            short: false,
            magic_offset: 0,
            always_display: false,
            magic: formats::pe::pe_magic(),
            parser: formats::pe::pe_parser,
            description: formats::pe::DESCRIPTION.to_string(),
            extractor: None,
        },
        // zlib
        signatures::Signature {
            name: "zlib".to_string(),
            // The magic bytes for this signature are only 2 bytes, only match on the beginning of a file
            short: true,
            magic_offset: 0,
            always_display: false,
            magic: formats::zlib::zlib_magic(),
            parser: formats::zlib::zlib_parser,
            description: formats::zlib::DESCRIPTION.to_string(),
            extractor: Some(formats::zlib::zlib_extractor()),
        },
        // gpg signed data
        signatures::Signature {
            name: "gpg_signed".to_string(),
            // The magic bytes for this signature are only 2 bytes, only match on the beginning of a file
            short: true,
            magic_offset: 0,
            always_display: false,
            magic: formats::gpg::gpg_signed_magic(),
            parser: formats::gpg::gpg_signed_parser,
            description: formats::gpg::GPG_SIGNED_DESCRIPTION.to_string(),
            extractor: Some(formats::gpg::gpg_extractor()),
        },
        // pem certificates
        signatures::Signature {
            name: "pem_certificate".to_string(),
            short: false,
            magic_offset: 0,
            always_display: false,
            magic: formats::pem::pem_certificate_magic(),
            parser: formats::pem::pem_parser,
            description: formats::pem::PEM_CERTIFICATE_DESCRIPTION.to_string(),
            extractor: Some(formats::pem::pem_certificate_extractor()),
        },
        // pem public keys
        signatures::Signature {
            name: "pem_public_key".to_string(),
            short: false,
            magic_offset: 0,
            always_display: true,
            magic: formats::pem::pem_public_key_magic(),
            parser: formats::pem::pem_parser,
            description: formats::pem::PEM_PUBLIC_KEY_DESCRIPTION.to_string(),
            extractor: Some(formats::pem::pem_key_extractor()),
        },
        // pem private keys
        signatures::Signature {
            name: "pem_private_key".to_string(),
            short: false,
            magic_offset: 0,
            always_display: true,
            magic: formats::pem::pem_private_key_magic(),
            parser: formats::pem::pem_parser,
            description: formats::pem::PEM_PRIVATE_KEY_DESCRIPTION.to_string(),
            extractor: Some(formats::pem::pem_key_extractor()),
        },
        // netgear chk
        signatures::Signature {
            name: "chk".to_string(),
            short: false,
            magic_offset: 0,
            always_display: false,
            magic: formats::chk::chk_magic(),
            parser: formats::chk::chk_parser,
            description: formats::chk::DESCRIPTION.to_string(),
            extractor: None,
        },
        // trx
        signatures::Signature {
            name: "trx".to_string(),
            short: false,
            magic_offset: 0,
            always_display: false,
            magic: formats::trx::trx_magic(),
            parser: formats::trx::trx_parser,
            description: formats::trx::DESCRIPTION.to_string(),
            extractor: Some(formats::trx::trx_extractor()),
        },
        // Motorola S-record
        signatures::Signature {
            name: "srecord".to_string(),
            short: false,
            magic_offset: 0,
            always_display: false,
            magic: formats::srec::srec_magic(),
            parser: formats::srec::srec_parser,
            description: formats::srec::SREC_DESCRIPTION.to_string(),
            extractor: Some(formats::srec::srec_extractor()),
        },
        // Motorola S-record (generic)
        signatures::Signature {
            name: "srecord_generic".to_string(),
            short: true,
            magic_offset: 0,
            always_display: false,
            magic: formats::srec::srec_short_magic(),
            parser: formats::srec::srec_parser,
            description: formats::srec::SREC_SHORT_DESCRIPTION.to_string(),
            extractor: Some(formats::srec::srec_extractor()),
        },
        // Android sparse
        signatures::Signature {
            name: "android_sparse".to_string(),
            short: false,
            magic_offset: 0,
            always_display: false,
            magic: formats::androidsparse::android_sparse_magic(),
            parser: formats::androidsparse::android_sparse_parser,
            description: formats::androidsparse::DESCRIPTION.to_string(),
            extractor: Some(formats::androidsparse::android_sparse_extractor()),
        },
        // device tree blob
        signatures::Signature {
            name: "dtb".to_string(),
            short: false,
            magic_offset: 0,
            always_display: false,
            magic: formats::dtb::dtb_magic(),
            parser: formats::dtb::dtb_parser,
            description: formats::dtb::DESCRIPTION.to_string(),
            extractor: Some(formats::dtb::dtb_extractor()),
        },
        // ubi
        signatures::Signature {
            name: "ubi".to_string(),
            short: false,
            magic_offset: 0,
            always_display: false,
            magic: formats::ubi::ubi_magic(),
            parser: formats::ubi::ubi_parser,
            description: formats::ubi::UBI_IMAGE_DESCRIPTION.to_string(),
            extractor: Some(formats::ubi::ubi_extractor()),
        },
        // ubifs
        signatures::Signature {
            name: "ubifs".to_string(),
            short: false,
            magic_offset: 0,
            always_display: false,
            magic: formats::ubi::ubifs_magic(),
            parser: formats::ubi::ubifs_parser,
            description: formats::ubi::UBI_FS_DESCRIPTION.to_string(),
            extractor: Some(formats::ubi::ubifs_extractor()),
        },
        // cfe bootloader
        signatures::Signature {
            name: "cfe".to_string(),
            short: false,
            magic_offset: 0,
            always_display: true,
            magic: formats::cfe::cfe_magic(),
            parser: formats::cfe::cfe_parser,
            description: formats::cfe::DESCRIPTION.to_string(),
            extractor: None,
        },
        // SEAMA firmware header
        signatures::Signature {
            name: "seama".to_string(),
            short: false,
            magic_offset: 0,
            always_display: true,
            magic: formats::seama::seama_magic(),
            parser: formats::seama::seama_parser,
            description: formats::seama::DESCRIPTION.to_string(),
            extractor: None,
        },
        // compress'd
        signatures::Signature {
            name: "compressd".to_string(),
            short: true,
            magic_offset: 0,
            always_display: false,
            magic: formats::compressd::compressd_magic(),
            parser: formats::compressd::compressd_parser,
            description: formats::compressd::DESCRIPTION.to_string(),
            extractor: Some(formats::sevenzip::sevenzip_extractor()),
        },
        // rar archive
        signatures::Signature {
            name: "rar".to_string(),
            short: false,
            magic_offset: 0,
            always_display: false,
            magic: formats::rar::rar_magic(),
            parser: formats::rar::rar_parser,
            description: formats::rar::DESCRIPTION.to_string(),
            extractor: Some(formats::rar::rar_extractor()),
        },
        // PNG image
        signatures::Signature {
            name: "png".to_string(),
            short: false,
            magic_offset: 0,
            always_display: false,
            magic: formats::png::png_magic(),
            parser: formats::png::png_parser,
            description: formats::png::DESCRIPTION.to_string(),
            extractor: Some(formats::png::png_extractor()),
        },
        // JPEG image
        signatures::Signature {
            name: "jpeg".to_string(),
            short: false,
            magic_offset: 0,
            always_display: false,
            magic: formats::jpeg::jpeg_magic(),
            parser: formats::jpeg::jpeg_parser,
            description: formats::jpeg::DESCRIPTION.to_string(),
            extractor: Some(formats::jpeg::jpeg_extractor()),
        },
        // arcadyan obfuscated lzma
        signatures::Signature {
            name: "arcadyan".to_string(),
            short: false,
            magic_offset: 0,
            always_display: false,
            magic: formats::arcadyan::obfuscated_lzma_magic(),
            parser: formats::arcadyan::obfuscated_lzma_parser,
            description: formats::arcadyan::DESCRIPTION.to_string(),
            extractor: Some(formats::arcadyan::obfuscated_lzma_extractor()),
        },
        // copyright text
        signatures::Signature {
            name: "copyright".to_string(),
            short: false,
            magic_offset: 0,
            always_display: false,
            magic: formats::copyright::copyright_magic(),
            parser: formats::copyright::copyright_parser,
            description: formats::copyright::DESCRIPTION.to_string(),
            extractor: None,
        },
        // WIND kernel version
        signatures::Signature {
            name: "wind_kernel".to_string(),
            short: false,
            magic_offset: 0,
            always_display: true,
            magic: formats::vxworks::wind_kernel_magic(),
            parser: formats::vxworks::wind_kernel_parser,
            description: formats::vxworks::WIND_KERNEL_DESCRIPTION.to_string(),
            extractor: None,
        },
        // vxworks symbol table
        signatures::Signature {
            name: "vxworks_symtab".to_string(),
            short: false,
            magic_offset: 0,
            always_display: true,
            magic: formats::vxworks::symbol_table_magic(),
            parser: formats::vxworks::symbol_table_parser,
            description: formats::vxworks::SYMTAB_DESCRIPTION.to_string(),
            extractor: Some(formats::vxworks::vxworks_symtab_extractor()),
        },
        // ecos mips exception handler
        signatures::Signature {
            name: "ecos".to_string(),
            short: false,
            magic_offset: 0,
            always_display: true,
            magic: formats::ecos::exception_handler_magic(),
            parser: formats::ecos::exception_handler_parser,
            description: formats::ecos::EXCEPTION_HANDLER_DESCRIPTION.to_string(),
            extractor: None,
        },
        // dmg
        signatures::Signature {
            name: "dmg".to_string(),
            short: false,
            magic_offset: 0,
            always_display: false,
            magic: formats::dmg::dmg_magic(),
            parser: formats::dmg::dmg_parser,
            description: formats::dmg::DESCRIPTION.to_string(),
            extractor: Some(formats::dmg::dmg_extractor()),
        },
        // riff
        signatures::Signature {
            name: "riff".to_string(),
            short: false,
            magic_offset: 0,
            always_display: false,
            magic: formats::riff::riff_magic(),
            parser: formats::riff::riff_parser,
            description: formats::riff::DESCRIPTION.to_string(),
            extractor: Some(formats::riff::riff_extractor()),
        },
        // openssl
        signatures::Signature {
            name: "openssl".to_string(),
            short: false,
            magic_offset: 0,
            always_display: true,
            magic: formats::openssl::openssl_crypt_magic(),
            parser: formats::openssl::openssl_crypt_parser,
            description: formats::openssl::DESCRIPTION.to_string(),
            extractor: Some(formats::encfw::encfw_extractor()),
        },
        // lzfse
        signatures::Signature {
            name: "lzfse".to_string(),
            short: false,
            magic_offset: 0,
            always_display: false,
            magic: formats::lzfse::lzfse_magic(),
            parser: formats::lzfse::lzfse_parser,
            description: formats::lzfse::DESCRIPTION.to_string(),
            extractor: Some(formats::lzfse::lzfse_extractor()),
        },
        // MBR
        signatures::Signature {
            name: "mbr".to_string(),
            short: true,
            magic_offset: formats::mbr::MAGIC_OFFSET,
            always_display: true,
            magic: formats::mbr::mbr_magic(),
            parser: formats::mbr::mbr_parser,
            description: formats::mbr::DESCRIPTION.to_string(),
            extractor: Some(formats::mbr::mbr_extractor()),
        },
        // tp-link
        signatures::Signature {
            name: "tplink".to_string(),
            short: false,
            magic_offset: 0,
            always_display: false,
            magic: formats::tplink::tplink_magic(),
            parser: formats::tplink::tplink_parser,
            description: formats::tplink::DESCRIPTION.to_string(),
            extractor: None,
        },
        // HP PJL
        signatures::Signature {
            name: "pjl".to_string(),
            short: false,
            magic_offset: 0,
            always_display: false,
            magic: formats::pjl::pjl_magic(),
            parser: formats::pjl::pjl_parser,
            description: formats::pjl::DESCRIPTION.to_string(),
            extractor: None,
        },
        // JBOOT ARM firmware image
        signatures::Signature {
            name: "jboot_arm".to_string(),
            short: false,
            magic_offset: 0,
            always_display: false,
            magic: formats::jboot::jboot_arm_magic(),
            parser: formats::jboot::jboot_arm_parser,
            description: formats::jboot::JBOOT_ARM_DESCRIPTION.to_string(),
            extractor: None,
        },
        // JBOOT STAG header
        signatures::Signature {
            name: "jboot_stag".to_string(),
            short: false,
            magic_offset: 0,
            always_display: false,
            magic: formats::jboot::jboot_stag_magic(),
            parser: formats::jboot::jboot_stag_parser,
            description: formats::jboot::JBOOT_STAG_DESCRIPTION.to_string(),
            extractor: None,
        },
        // JBOOT SCH2 header
        signatures::Signature {
            name: "jboot_sch2".to_string(),
            short: false,
            magic_offset: 0,
            always_display: false,
            magic: formats::jboot::jboot_sch2_magic(),
            parser: formats::jboot::jboot_sch2_parser,
            description: formats::jboot::JBOOT_SCH2_DESCRIPTION.to_string(),
            extractor: Some(formats::jboot::sch2_extractor()),
        },
        // pcap-ng
        signatures::Signature {
            name: "pcapng".to_string(),
            short: false,
            magic_offset: 0,
            always_display: false,
            magic: formats::pcap::pcapng_magic(),
            parser: formats::pcap::pcapng_parser,
            description: formats::pcap::PCAPNG_DESCRIPTION.to_string(),
            extractor: Some(formats::pcap::pcapng_extractor()),
        },
        // RSA encrypted data
        signatures::Signature {
            name: "rsa".to_string(),
            short: false,
            magic_offset: 0,
            always_display: true,
            magic: formats::rsa::rsa_magic(),
            parser: formats::rsa::rsa_parser,
            description: formats::rsa::DESCRIPTION.to_string(),
            extractor: None,
        },
        // GIF image
        signatures::Signature {
            name: "gif".to_string(),
            short: false,
            magic_offset: 0,
            always_display: false,
            magic: formats::gif::gif_magic(),
            parser: formats::gif::gif_parser,
            description: formats::gif::DESCRIPTION.to_string(),
            extractor: Some(formats::gif::gif_extractor()),
        },
        // SVG image
        signatures::Signature {
            name: "svg".to_string(),
            short: false,
            magic_offset: 0,
            always_display: false,
            magic: formats::svg::svg_magic(),
            parser: formats::svg::svg_parser,
            description: formats::svg::DESCRIPTION.to_string(),
            extractor: Some(formats::svg::svg_extractor()),
        },
        // Linux ARM64 boot image
        signatures::Signature {
            name: "linux_arm64_boot_image".to_string(),
            short: false,
            magic_offset: 0,
            always_display: false,
            magic: formats::linux::linux_arm64_boot_image_magic(),
            parser: formats::linux::linux_arm64_boot_image_parser,
            description: formats::linux::LINUX_ARM64_BOOT_IMAGE_DESCRIPTION.to_string(),
            extractor: None,
        },
        // FAT
        signatures::Signature {
            name: "fat".to_string(),
            short: true,
            magic_offset: formats::fat::MAGIC_OFFSET,
            always_display: false,
            magic: formats::fat::fat_magic(),
            parser: formats::fat::fat_parser,
            description: formats::fat::DESCRIPTION.to_string(),
            extractor: Some(extractors::tsk::tsk_extractor()),
        },
        // EFI GPT
        signatures::Signature {
            name: "efigpt".to_string(),
            short: false,
            magic_offset: 0,
            always_display: false,
            magic: formats::efigpt::efigpt_magic(),
            parser: formats::efigpt::efigpt_parser,
            description: formats::efigpt::DESCRIPTION.to_string(),
            extractor: Some(formats::sevenzip::sevenzip_extractor()),
        },
        // RTK firmware header
        signatures::Signature {
            name: "rtk".to_string(),
            short: true,
            magic_offset: 0,
            always_display: false,
            magic: formats::rtk::rtk_magic(),
            parser: formats::rtk::rtk_parser,
            description: formats::rtk::DESCRIPTION.to_string(),
            extractor: None,
        },
        // AES S-Box
        signatures::Signature {
            name: "aes_sbox".to_string(),
            short: false,
            magic_offset: 0,
            always_display: false,
            magic: formats::aes::aes_sbox_magic(),
            parser: formats::aes::aes_sbox_parser,
            description: formats::aes::DESCRIPTION_AES_SBOX.to_string(),
            extractor: None,
        },
        // AES Forward table
        signatures::Signature {
            name: "aes_forward_table".to_string(),
            short: false,
            magic_offset: 0,
            always_display: false,
            magic: formats::aes::aes_forward_table_magic(),
            parser: formats::aes::aes_forward_table_parser,
            description: formats::aes::DESCRIPTION_AES_FT.to_string(),
            extractor: None,
        },
        // AES Reverse table
        signatures::Signature {
            name: "aes_reverse_table".to_string(),
            short: false,
            magic_offset: 0,
            always_display: false,
            magic: formats::aes::aes_reverse_table_magic(),
            parser: formats::aes::aes_reverse_table_parser,
            description: formats::aes::DESCRIPTION_AES_RT.to_string(),
            extractor: None,
        },
        // AES RCON
        signatures::Signature {
            name: "aes_rcon".to_string(),
            short: false,
            magic_offset: 0,
            always_display: false,
            magic: formats::aes::aes_rcon_magic(),
            parser: formats::aes::aes_rcon_parser,
            description: formats::aes::DESCRIPTION_AES_RCON.to_string(),
            extractor: None,
        },
        // Accelerated AES
        signatures::Signature {
            name: "aes_acceleration_table".to_string(),
            short: false,
            magic_offset: 0,
            always_display: false,
            magic: formats::aes::aes_acceleration_table_magic(),
            parser: formats::aes::aes_acceleration_table_parser,
            description: formats::aes::DESCRIPTION_AES_ACC.to_string(),
            extractor: None,
        },
        // LUKS
        signatures::Signature {
            name: "luks".to_string(),
            short: false,
            magic_offset: 0,
            always_display: false,
            magic: formats::luks::luks_magic(),
            parser: formats::luks::luks_parser,
            description: formats::luks::DESCRIPTION.to_string(),
            extractor: None,
        },
        // TP-Link RTOS
        signatures::Signature {
            name: "tplink_rtos".to_string(),
            short: false,
            magic_offset: 0,
            always_display: false,
            magic: formats::tplink::tplink_rtos_magic(),
            parser: formats::tplink::tplink_rtos_parser,
            description: formats::tplink::RTOS_DESCRIPTION.to_string(),
            extractor: None,
        },
        // BIN firmware header
        signatures::Signature {
            name: "binhdr".to_string(),
            short: false,
            magic_offset: 0,
            always_display: false,
            magic: formats::binhdr::bin_hdr_magic(),
            parser: formats::binhdr::bin_hdr_parser,
            description: formats::binhdr::DESCRIPTION.to_string(),
            extractor: None,
        },
        // Autel obfuscated firmware
        signatures::Signature {
            name: "autel".to_string(),
            short: false,
            magic_offset: 0,
            always_display: false,
            magic: formats::autel::autel_magic(),
            parser: formats::autel::autel_parser,
            description: formats::autel::DESCRIPTION.to_string(),
            extractor: Some(formats::autel::autel_extractor()),
        },
        // NTFS
        signatures::Signature {
            name: "ntfs".to_string(),
            short: false,
            magic_offset: 0,
            always_display: false,
            magic: formats::ntfs::ntfs_magic(),
            parser: formats::ntfs::ntfs_parser,
            description: formats::ntfs::DESCRIPTION.to_string(),
            extractor: Some(extractors::tsk::tsk_extractor()),
        },
        // APFS
        signatures::Signature {
            name: "apfs".to_string(),
            short: false,
            magic_offset: 0,
            always_display: false,
            magic: formats::apfs::apfs_magic(),
            parser: formats::apfs::apfs_parser,
            description: formats::apfs::DESCRIPTION.to_string(),
            extractor: Some(formats::sevenzip::sevenzip_extractor()),
        },
        // BTRFS
        signatures::Signature {
            name: "btrfs".to_string(),
            short: false,
            magic_offset: 0,
            always_display: true,
            magic: formats::btrfs::btrfs_magic(),
            parser: formats::btrfs::btrfs_parser,
            description: formats::btrfs::DESCRIPTION.to_string(),
            extractor: None,
        },
        // WinCE
        signatures::Signature {
            name: "wince".to_string(),
            short: false,
            magic_offset: 0,
            always_display: false,
            magic: formats::wince::wince_magic(),
            parser: formats::wince::wince_parser,
            description: formats::wince::DESCRIPTION.to_string(),
            extractor: Some(formats::wince::wince_extractor()),
        },
        // Dahua ZIP
        signatures::Signature {
            name: "dahua_zip".to_string(),
            short: false,
            magic_offset: 0,
            always_display: false,
            magic: formats::dahua_zip::dahua_zip_magic(),
            parser: formats::dahua_zip::dahua_zip_parser,
            description: formats::dahua_zip::DESCRIPTION.to_string(),
            extractor: Some(formats::dahua_zip::dahua_zip_extractor()),
        },
        // DLink MH01
        signatures::Signature {
            name: "mh01".to_string(),
            short: false,
            magic_offset: 0,
            always_display: false,
            magic: formats::mh01::mh01_magic(),
            parser: formats::mh01::mh01_parser,
            description: formats::mh01::DESCRIPTION.to_string(),
            extractor: Some(formats::mh01::mh01_extractor()),
        },
        // CSman DAT
        signatures::Signature {
            name: "csman".to_string(),
            short: true,
            magic_offset: 0,
            always_display: false,
            magic: formats::csman::csman_magic(),
            parser: formats::csman::csman_parser,
            description: formats::csman::DESCRIPTION.to_string(),
            extractor: Some(formats::csman::csman_extractor()),
        },
        // DirectX ByteCode
        signatures::Signature {
            name: "dxbc".to_string(),
            short: false,
            magic_offset: 0,
            always_display: false,
            magic: formats::dxbc::dxbc_magic(),
            parser: formats::dxbc::dxbc_parser,
            description: formats::dxbc::DESCRIPTION.to_string(),
            extractor: Some(formats::dxbc::dxbc_extractor()),
        },
        // D-Link TLV firmware
        signatures::Signature {
            name: "dlink_tlv".to_string(),
            short: false,
            magic_offset: 0,
            always_display: false,
            magic: formats::dlink_tlv::dlink_tlv_magic(),
            parser: formats::dlink_tlv::dlink_tlv_parser,
            description: formats::dlink_tlv::DESCRIPTION.to_string(),
            extractor: Some(formats::encfw::encfw_extractor()),
        },
        // DLKE encrypted firmware
        signatures::Signature {
            name: "dlke".to_string(),
            short: false,
            magic_offset: 0,
            always_display: false,
            magic: formats::dlke::dlke_magic(),
            parser: formats::dlke::dlke_parser,
            description: formats::dlke::DESCRIPTION.to_string(),
            extractor: Some(formats::encfw::encfw_extractor()),
        },
        // SHRS encrypted firmware
        signatures::Signature {
            name: "shrs".to_string(),
            short: false,
            magic_offset: 0,
            always_display: false,
            magic: formats::shrs::shrs_magic(),
            parser: formats::shrs::shrs_parser,
            description: formats::shrs::DESCRIPTION.to_string(),
            extractor: Some(formats::encfw::encfw_extractor()),
        },
        // PKCS DER hashes
        signatures::Signature {
            name: "pkcs_der_hash".to_string(),
            short: false,
            magic_offset: 0,
            always_display: false,
            magic: formats::pkcs_der::der_hash_magic(),
            parser: formats::pkcs_der::der_hash_parser,
            description: formats::pkcs_der::DESCRIPTION.to_string(),
            extractor: None,
        },
        // LogFS
        signatures::Signature {
            name: "logfs".to_string(),
            short: false,
            magic_offset: 0,
            always_display: false,
            magic: formats::logfs::logfs_magic(),
            parser: formats::logfs::logfs_parser,
            description: formats::logfs::DESCRIPTION.to_string(),
            extractor: None,
        },
        // encrpted_img
        signatures::Signature {
            name: "encrpted_img".to_string(),
            short: true,
            magic_offset: 0,
            always_display: false,
            magic: formats::encrpted_img::encrpted_img_magic(),
            parser: formats::encrpted_img::encrpted_img_parser,
            description: formats::encrpted_img::DESCRIPTION.to_string(),
            extractor: Some(formats::encfw::encfw_extractor()),
        },
        // Android boot image
        signatures::Signature {
            name: "android_bootimg".to_string(),
            short: false,
            magic_offset: 0,
            always_display: false,
            magic: formats::android_bootimg::android_bootimg_magic(),
            parser: formats::android_bootimg::android_bootimg_parser,
            description: formats::android_bootimg::DESCRIPTION.to_string(),
            extractor: None,
        },
        // uboot
        signatures::Signature {
            name: "uboot".to_string(),
            short: false,
            magic_offset: 0,
            always_display: true,
            magic: formats::uboot::uboot_magic(),
            parser: formats::uboot::uboot_parser,
            description: formats::uboot::DESCRIPTION.to_string(),
            extractor: None,
        },
        // dms firmware
        signatures::Signature {
            name: "dms".to_string(),
            short: false,
            magic_offset: 0,
            always_display: false,
            magic: formats::dms::dms_magic(),
            parser: formats::dms::dms_parser,
            description: formats::dms::DESCRIPTION.to_string(),
            extractor: Some(extractors::swapped::swapped_extractor_u16()),
        },
        // dkbs firmware
        signatures::Signature {
            name: "dkbs".to_string(),
            short: false,
            magic_offset: 0,
            always_display: false,
            magic: formats::dkbs::dkbs_magic(),
            parser: formats::dkbs::dkbs_parser,
            description: formats::dkbs::DESCRIPTION.to_string(),
            extractor: Some(formats::encfw::encfw_extractor()),
        },
        // known encrypted firmware
        signatures::Signature {
            name: "encfw".to_string(),
            short: true,
            magic_offset: 0,
            always_display: true,
            magic: formats::encfw::encfw_magic(),
            parser: formats::encfw::encfw_parser,
            description: formats::encfw::DESCRIPTION.to_string(),
            extractor: Some(formats::encfw::encfw_extractor()),
        },
        // matter ota firmware
        signatures::Signature {
            name: "matter_ota".to_string(),
            short: true,
            magic_offset: 0,
            always_display: false,
            magic: formats::matter_ota::matter_ota_magic(),
            parser: formats::matter_ota::matter_ota_parser,
            description: formats::matter_ota::DESCRIPTION.to_string(),
            extractor: Some(formats::matter_ota::matter_ota_extractor()),
        },
        // DPAPI blob data
        signatures::Signature {
            name: "dpapi".to_string(),
            short: true,
            magic_offset: 0,
            always_display: true,
            magic: formats::dpapi::dpapi_magic(),
            parser: formats::dpapi::dpapi_parser,
            description: formats::dpapi::DESCRIPTION.to_string(),
            extractor: None,
        },
        // QEMU QCOW image
        signatures::Signature {
            name: "qcow".to_string(),
            short: true,
            magic_offset: 0,
            always_display: true,
            magic: formats::qcow::qcow_magic(),
            parser: formats::qcow::qcow_parser,
            description: formats::qcow::DESCRIPTION.to_string(),
            extractor: None,
        },
        // ARJ archive
        signatures::Signature {
            name: "arj".to_string(),
            short: false,
            magic_offset: 0,
            always_display: false,
            magic: formats::arj::arj_magic(),
            parser: formats::arj::arj_parser,
            description: formats::arj::DESCRIPTION.to_string(),
            extractor: Some(formats::sevenzip::sevenzip_extractor()),
        },
        // MD5 hashes
        signatures::Signature {
            name: "md5".to_string(),
            short: false,
            magic_offset: 0,
            always_display: false,
            magic: formats::hashes::md5_magic(),
            parser: formats::hashes::md5_parser,
            description: formats::hashes::MD5_DESCRIPTION.to_string(),
            extractor: None,
        },
        // Broadcom ProgramStore firmware
        signatures::Signature {
            name: "program_store".to_string(),
            short: false,
            magic_offset: 0,
            always_display: false,
            magic: formats::program_store::program_store_magic(),
            parser: formats::program_store::program_store_parser,
            description: formats::program_store::DESCRIPTION.to_string(),
            extractor: Some(formats::program_store::program_store_extractor()),
        },
    ];

    binary_signatures
}
